## GENERATING FAKE DATA

In [337]:
from matplotlib.pylab import rand
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from faker import Faker
import random


fake = Faker('id_ID') #clone of indonesian locale
random.seed(11)  
fake.seed_instance(11)

# target number of rows
n_records = 1234

package_type = ['solo', 'family', 'honeymoon', 'group']
months = pd.date_range(start='2023-01-01', periods=12, freq='M').strftime('%Y-%m').tolist()
gender = ['male', 'female', 'other']
customer_type = ['regular', 'new']


# function to generate random email based on name
def generate_email(name):
    name = name
    domains =  ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com']
    domain = random.choice(domains)
    return f"{name}@{domain}"

# Generate random data - 1st table: customer data
customer_names = [fake.name() for _ in range(n_records)]

# id, name, gender, age, nationality, email, customer_type
customer_data = {
    'customer_id': [f"MY{1000 + i}" for i in range(n_records)],
    'customer_name': customer_names,
    'gender': [random.choice(gender) for _ in range(n_records)],
    'age': [fake.random_int(min=18, max=70) for _ in range(n_records)],
    'email': [generate_email(name) for name in customer_names],
    'customer_type': [random.choice(customer_type) for _ in range(n_records)]    
}

customers = pd.DataFrame(customer_data)
customers.head()

C:\Users\User\AppData\Local\Temp\ipykernel_5216\3669169723.py:17: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  months = pd.date_range(start='2023-01-01', periods=12, freq='M').strftime('%Y-%m').tolist()

,customer_id,customer_name,gender,age,email,customer_type
0,MY1000,Zelaya Purwanti,female,39,Zelaya Purwanti@hotmail.com,new
1,MY1001,"Dr. Mila Melani, M.Farm",other,52,"Dr. Mila Melani, M.Farm@gmail.com",regular
2,MY1002,Cengkal Mulyani,female,45,Cengkal Mulyani@outlook.com,new
3,MY1003,Siti Susanti,female,50,Siti Susanti@outlook.com,new
4,MY1004,"R.M. Bakiono Hassanah, S.Pd",other,53,"R.M. Bakiono Hassanah, S.Pd@gmail.com",new

In [338]:
# Generate random data - 2nd table: travle_package
# col name: package_id, package_name, package_type, duration_dayys, price_per_pax, category

destination_malaysia = ['Kuala Lumpur', 'Penang', 'Melaka', 'Langkawi', 'Pulau Perhentian', 'Pulau Redang', 'Pulau Tioman', 'Pulau Sipadan', 'Cameron Highlands', 'Kota Kinabalu', 'Taman Negara', 'Borneo', 'Putrajaya'] 
southeast_asia_destinations = [
    "Bali","Jakarta","Yogyakarta","Bangkok","Chiang Mai","Phuket","Krabi","Hanoi","Ho Chi Minh City","Halong Bay","Sapa","Nha Trang","Luang Prabang","Vientiane","Phnom Penh","Siem Reap","Bagan","Yangon",              
    "Singapore","Manila","Cebu","Boracay","Brunei","Dili","Lombok","Komodo Island" ]

all_destinations = destination_malaysia + southeast_asia_destinations
n_package = len(all_destinations)

# Function to determine base price_per_pax for each package based on type and destination
def get_price(name, type):
    if name in destination_malaysia:
        if type == 'family':
            return fake.random_int(500, 800)
        elif type == 'group': 
            return fake.random_int(800, 1000)
        elif type == 'honeymoon':
            return fake.random_int(1000, 2000)
        elif type == 'solo':
            return fake.random_int(800, 1200)
    elif name in southeast_asia_destinations:
        if type == 'family':
            return fake.random_int(1500, 1900)
        elif type == 'group':
            return fake.random_int(1700, 2700)
        elif type == 'honeymoon':
            return fake.random_int(2500, 3500)
        elif type == 'solo':
            return fake.random_int(1700, 3000)
        
# Function to generate category based on package_type

def get_category(type):
    if type == 'honeymoon':
        return 'beach'
    else:
        return random.choice(['adventure', 'cultural', 'eco'])
    
    
package_name = [random.choice(all_destinations) for _ in range(n_package)]
package_type = [random.choice(package_type) for _ in range(n_package)]

price_per_pax = [get_price(name, type) for name, type in zip(package_name, package_type)]

travel = {
    'package_id': [f"PC{10 + i}" for i in range(n_package)],
    'package_name': package_name,
    'package_type': package_type,
    'duration_days': [fake.random_int(min=2, max=7) for _ in range(n_package)],
    'price_per_pax': price_per_pax,
    'category': [get_category(type) for type in package_type],
    'destination': package_name
}

travel_package = pd.DataFrame(travel)
travel_package.head()

,package_id,package_name,package_type,duration_days,price_per_pax,category,destination
0,PC10,Kota Kinabalu,family,3,530,eco,Kota Kinabalu
1,PC11,Langkawi,family,3,522,adventure,Langkawi
2,PC12,Taman Negara,group,3,900,cultural,Taman Negara
3,PC13,Krabi,solo,3,1825,eco,Krabi
4,PC14,Pulau Sipadan,family,5,762,adventure,Pulau Sipadan

In [339]:
# Generate data - 3rd table: Travel_guide
# staff_id, staff_name, role, working_status, commission_rate, 

guide_name = ['Nasrul', 'Khair', 'Intan', 'Amira', 'Nuha', 'Alissa', 'Waddah', 'Izzah', 'Nasir']
role = ['main_guide', 'assistant_guide']
working_status = ['permanent', 'contract', 'freelance']

#generate functions to determine comission rate based on working_status

def get_comission_rate(working_status):
    if working_status == 'freelance':
        return fake.random_int(10, 15) / 100  
    elif working_status == 'contract':
        return fake.random_int(7, 13) / 100
    else:
        return fake.random_int(5, 10) / 100
    
staff_data = {
    'staff_id': [str(i).zfill(4) for i in range(101, 101 + len(guide_name))],
    'staff_name': guide_name,
    'role': [random.choice(role) for _ in range(len(guide_name))],
    'working_status': [random.choice(working_status) for _ in guide_name]
}

travel_guide = pd.DataFrame(staff_data)
    
# col comission_rate
travel_guide['comission_rate'] = travel_guide['working_status'].apply(get_comission_rate)
travel_guide.head()

  staff_id staff_name             role working_status  comission_rate
0     0101     Nasrul  assistant_guide      permanent            0.09
1     0102      Khair  assistant_guide       contract            0.12
2     0103      Intan  assistant_guide      permanent            0.06
3     0104      Amira       main_guide       contract            0.13
4     0105       Nuha  assistant_guide      permanent            0.09

In [340]:
# Generate random data - 4th table: sales

# listing customer_id and package_id for later use
customer_id = list(customer['customer_id'])
package_id = list(travel_package['package_id'])
guide_id = list(travel_guide['staff_id'])

# Create mapping: package_id → package_type
package_type_map = travel_package.set_index('package_id')['package_type'].to_dict()

#payment_options 
payment_status = ['paid', 'pending', 'refunded']
payment_method = ['credit_card', 'online_transfer', 'cash', 'eWallet']


# Function to determine num_of_pax
def get_pax(package_type):
    ptype = package_type.lower()
    if ptype == 'family':
        return fake.random_int(3, 7)
    elif ptype == 'honeymoon':
        return 2
    elif ptype == 'group':
        return fake.random_int(12, 25)
    else:
        return 1  # fallback

# Number of records to generate
total_sales_record = 2561

# Randomly assign customer_id, package_id and guide_id
booking_customer_ids = [random.choice(customer_id) for _ in range(total_sales_record)]
booking_package_ids = [random.choice(package_id) for _ in range(total_sales_record)]

# Use package_id to get package_type and then determine pax
booking_package_types = [package_type_map[pid] for pid in booking_package_ids]
num_of_pax = [get_pax(ptype) for ptype in booking_package_types]
booking_dates =  [fake.date_between(start_date='-1y', end_date='today') for _ in range(total_sales_record)]

# Generate the full booking dataset
booking_data = {
    'booking_id': [f"BK{100 + i}" for i in range(total_sales_record)],
    'customer_id': booking_customer_ids,
    'package_id': booking_package_ids,
    'guide_id': [random.choice(guide_id) for _ in range(total_sales_record)],
    'booking_date': booking_dates,
    'travel_date': [fake.date_between(start_date=date, end_date=date + pd.Timedelta(days=365))for date in booking_dates],
    'num_of_pax': num_of_pax,
    'discount_promotion': [fake.random_int(min=0, max=17) for _ in range(total_sales_record)],
    'channel': [random.choice(['online', 'offline', 'agent', 'walk in']) for _ in range(total_sales_record)],
    'payment_status': [random.choice(payment_status) for _ in range(total_sales_record)],
    'payment_method': [random.choice(payment_method) for _ in range(total_sales_record)]
}

# Create DataFrame
sales = pd.DataFrame(booking_data)
sales.head()

,booking_id,customer_id,package_id,guide_id,booking_date,travel_date,num_of_pax,discount_promotion,channel,payment_status,payment_method
0,BK100,MY1195,PC31,0104,2024-11-17,2025-08-19,2,10,online,refunded,credit_card
1,BK101,MY1350,PC39,0102,2025-05-27,2025-07-24,22,5,online,pending,online_transfer
2,BK102,MY1673,PC18,0104,2024-10-26,2025-01-06,25,10,online,paid,cash
3,BK103,MY1410,PC38,0102,2024-10-16,2025-09-11,1,6,walk in,paid,credit_card
4,BK104,MY1457,PC27,0103,2025-02-01,2025-07-30,1,10,offline,paid,cash

In [341]:
# Generate random data - 5th table: feedback
# Feedback comments

feedback_comments = [
    "The hotel and guide exceeded our expectations!",
    "Everything was well organized and smooth.",
    "Truly a memorable adventure for our family!",
    "Beautiful destinations and a relaxing itinerary.",
    "Highly recommend this package to others.",
    "Some meals weren’t up to standard.",
    "Overall good, but the hotel could be better.",
    "Tour guide was late and disorganized.",
    "The schedule was a bit tight but manageable.",
    "Too many hidden charges in the package."
]

# Recommendation logic
def recommendation(score):
    if score >= 7:
        return 'Yes'
    elif score < 4:
        return 'No'
    else:
        return random.choice(['Yes', 'No'])

# Generate feedback data
num_feedbacks = 320
feedback_data = []

for i in range(1, num_feedbacks + 1):
    row = sales.sample(n=1).iloc[0]
    score = random.randint(1, 10)

    travel_date = pd.to_datetime(row["travel_date"])
    feedback_date = fake.date_between(start_date=travel_date, end_date=travel_date + pd.Timedelta(days=90))

    feedback_data.append({
        "feedback_id": f"FB{i:03}",
        "package_id": row["package_id"],
        "booking_id": row["booking_id"],
        "SatisfactionScore": score,
        "FeedbackDate": feedback_date,
        "Comments": random.choice(feedback_comments),
        "Rating_Hotel": random.randint(2, 5),
        "Rating_Guide": random.randint(2, 5),
        "Rating_Itinerary": random.randint(2, 5),
        "WouldRecommend": recommendation(score)
    })

feedback = pd.DataFrame(feedback_data)
feedback.head()

,feedback_id,package_id,booking_id,SatisfactionScore,FeedbackDate,Comments,Rating_Hotel,Rating_Guide,Rating_Itinerary,WouldRecommend
0,FB001,PC16,BK2462,8,2025-11-23,Highly recommend this package to others.,2,2,3,Yes
1,FB002,PC43,BK1685,1,2026-02-25,Highly recommend this package to others.,3,5,2,No
2,FB003,PC34,BK2433,4,2025-02-09,Everything was well organized and smooth.,5,3,4,Yes
3,FB004,PC29,BK1715,8,2026-04-12,The hotel and guide exceeded our expectations!,5,5,3,Yes
4,FB005,PC40,BK1196,3,2025-03-27,Beautiful destinations and a relaxing itinerary.,3,3,4,No

In [342]:
# Generate data - 6th table: Refund
# refund_id, booking_id, refund_date, refund_amount, refund_percentage,reason

# refund reasons
refund_reasons = [
        'Cancellation by customer',
        'Package change request',
        'Travel restrictions',
        'Unforeseen circumstances',
        'Service quality issues',
        'Booking errors',
        'Natural disasters',
        'Health emergencies',
        'Other']

refund_statuses = ['Pending', 'Approved', 'Rejected']

refund_rows = 9

# Sample from sales to extract booking_id and customer_id together
sampled_sales = sales.sample(n=refund_rows).reset_index(drop=True)

refund_data = []

for i in range(refund_rows):
    booking_id = sampled_sales.loc[i, 'booking_id']
    customer_id = sampled_sales.loc[i, 'customer_id']
    booking_date = pd.to_datetime(sampled_sales.loc[i, 'booking_date'])
    refund_date = booking_date + pd.Timedelta(days=random.randint(1, 30))
    refund_amount = random.randint(100, 1000)  # Simulated refund amount
    refund_percentage = round(random.uniform(5, 30), 2)  # e.g. 5.75%
    reason = random.choice(refund_reasons)
    status = random.choice(refund_statuses)

    refund_data.append({
        'refund_id': f'RF{i+1:03}',
        'booking_id': booking_id,
        'customer_id': customer_id,
        'refund_date': refund_date.date(),
        'refund_amount': refund_amount,
        'refund_percentage': refund_percentage,
        'reason': reason,
        'refund_status': status
    })

refund = pd.DataFrame(refund_data)
refund.head()

,refund_id,booking_id,customer_id,refund_date,refund_amount,refund_percentage,reason,refund_status
0,RF001,BK167,MY1058,2024-08-22,284,19.80,Cancellation by customer,Approved
1,RF002,BK1129,MY2069,2024-09-18,355,11.86,Service quality issues,Approved
2,RF003,BK2012,MY1523,2024-08-07,604,27.94,Natural disasters,Rejected
3,RF004,BK1659,MY2086,2025-02-05,265,6.30,Travel restrictions,Pending
4,RF005,BK1271,MY1499,2024-09-30,116,13.08,Travel restrictions,Pending

## TRANSFORMATION

In [343]:
# 1. customers table
customers['email'] = customers['email'].str.replace(' ', '_').str.replace(',','').str.lower()
customers.head()

,customer_id,customer_name,gender,age,email,customer_type
0,MY1000,Zelaya Purwanti,female,39,zelaya_purwanti@hotmail.com,new
1,MY1001,"Dr. Mila Melani, M.Farm",other,52,dr._mila_melani_m.farm@gmail.com,regular
2,MY1002,Cengkal Mulyani,female,45,cengkal_mulyani@outlook.com,new
3,MY1003,Siti Susanti,female,50,siti_susanti@outlook.com,new
4,MY1004,"R.M. Bakiono Hassanah, S.Pd",other,53,r.m._bakiono_hassanah_s.pd@gmail.com,new

In [344]:
# 2. feedback table

feedback['FeedbackDate'] = pd.to_datetime(feedback['FeedbackDate'])


feedback.rename(columns = {
    'SatisfactionScore': 'satisfaction_score',
    'Comments': 'feedback_comments',
    'Rating_Hotel': 'rating_hotel',
    'Rating_Guide': 'rating_guide',
    'Rating_Itinerary': 'rating_itinerary',
    'WouldRecommend': 'would_recommend'
}, inplace=True)

feedback.head()

,feedback_id,package_id,booking_id,satisfaction_score,FeedbackDate,feedback_comments,rating_hotel,rating_guide,rating_itinerary,would_recommend
0,FB001,PC16,BK2462,8,2025-11-23,Highly recommend this package to others.,2,2,3,Yes
1,FB002,PC43,BK1685,1,2026-02-25,Highly recommend this package to others.,3,5,2,No
2,FB003,PC34,BK2433,4,2025-02-09,Everything was well organized and smooth.,5,3,4,Yes
3,FB004,PC29,BK1715,8,2026-04-12,The hotel and guide exceeded our expectations!,5,5,3,Yes
4,FB005,PC40,BK1196,3,2025-03-27,Beautiful destinations and a relaxing itinerary.,3,3,4,No

In [345]:
# 3. refund table

refund['refund_date'] = pd.to_datetime(refund['refund_date'])
refund.dtypes

refund_id                    object
booking_id                   object
customer_id                  object
refund_date          datetime64[ns]
refund_amount                 int64
refund_percentage           float64
reason                       object
refund_status                object
dtype: object

In [346]:
# 4. travel_guide table
travel_guide['staff_name'] = travel_guide['staff_name'].str.lower()
travel_guide['role'] = travel_guide['role'].str.replace('_', ' ')
travel_guide.head()

  staff_id staff_name             role working_status  comission_rate
0     0101     nasrul  assistant guide      permanent            0.09
1     0102      khair  assistant guide       contract            0.12
2     0103      intan  assistant guide      permanent            0.06
3     0104      amira       main guide       contract            0.13
4     0105       nuha  assistant guide      permanent            0.09

In [347]:
# 5. travel_package table
travel_package['package_name'] = travel_package['package_name'].str.lower()
travel_package['destination'] = travel_package['destination'].str.lower()
travel_package.dtypes

package_id       object
package_name     object
package_type     object
duration_days     int64
price_per_pax     int64
category         object
destination      object
dtype: object

In [348]:
# 6. sales table
#sales.dtypes

sales['booking_date'] = pd.to_datetime(sales['booking_date'])
sales['travel_date'] = pd.to_datetime(sales['travel_date'])
sales.dtypes

booking_id                    object
customer_id                   object
package_id                    object
guide_id                      object
booking_date          datetime64[ns]
travel_date           datetime64[ns]
num_of_pax                     int64
discount_promotion             int64
channel                       object
payment_status                object
payment_method                object
dtype: object

In [349]:
# Saving all csv files
customers.to_csv(r"C:\Users\User\Desktop\Data Analyst\End To End Project\PPNJ\dim_customer.csv", index=False)
travel_package.to_csv(r"C:\Users\User\Desktop\Data Analyst\End To End Project\PPNJ\dim_travel_package.csv", index=False)            
sales.to_csv(r"C:\Users\User\Desktop\Data Analyst\End To End Project\PPNJ\fact_sales.csv", index=False)
feedback.to_csv(r"C:\Users\User\Desktop\Data Analyst\End To End Project\PPNJ\dim_feedback.csv", index=False)
travel_guide.to_csv(r"C:\Users\User\Desktop\Data Analyst\End To End Project\PPNJ\dim_travel_guide.csv", index=False)
refund.to_csv(r"C:\Users\User\Desktop\Data Analyst\End To End Project\PPNJ\dim_refund.csv", index=False)